#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <string.h>
#include <stdbool.h>
#include <inttypes.h>

void BakeFile(char* path, char* name);

FILE* assets;

void main() {
	assets = fopen("assets.h", "wb");
	assert(assets);
	fprintf(assets, "%s\n", "/*******************************");
	fprintf(assets, "%s\n", " *     generated by bake.c     *");
	fprintf(assets, "%s\n", " *******************************/");

	BakeFile("src/layout.frag", "layoutFragmentShaderSource");
	BakeFile("src/layout.vert", "layoutVertexShaderSource");

	fclose(assets);
}

void BakeFile(char* path, char* name) {

	FILE* fp = fopen(path,"rb");
	assert(fp);
	fseek(fp,0,SEEK_END);
	int len = ftell(fp);
	fseek(fp,0,SEEK_SET);
	assert(len > -1);
	char* text = malloc(len+1);
	assert(text);
	text[len] = '\0';
	fread(text,1,len,fp);
	fclose(fp);

	fprintf(assets, "const char %s[] = { ", name);
	for(int i = 0;i<len;i++) {
		if (i == len-1) {
			fprintf(assets, "%d, 0 };\n", text[i]);
		} else {
			fprintf(assets, "%d, ", text[i]);
		}
	}

	free(text);
}
